{% set version = "3.1.5" %}

package:
  name: pyscipopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v{{ version }}.tar.gz
  sha256: dc4040a38f79fd104947b1e8dec97be6f95a2fb3ca1ad944eeccc10a8d493c6b

build:
  number: 0
  script: '"${PYTHON}" -m pip install --no-deps .'  # [unix]
  script: '"%PYTHON%"  -m pip install --no-deps .'  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - scip
    - python
    - pip
    - cython >=0.29.21
  run:
    - python

test:
  imports:
    - pyscipopt
    - pyscipopt.scip
  commands:
    - python -c "import pyscipopt.scip; pyscipopt.scip.Model()"

about:
  home: https://github.com/scipopt/PySCIPOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  doc_url: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
